//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace App4.Authentication {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuthenticationSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseResult))]
    public partial class Authentication : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWebSitePropertiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetPasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Authentication() {
            this.Url = "http://95.6.50.139:90/services/Authentication.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event LogoutCompletedEventHandler LogoutCompleted;
        
        /// <remarks/>
        public event GetWebSitePropertiesCompletedEventHandler GetWebSitePropertiesCompleted;
        
        /// <remarks/>
        public event SetPasswordCompletedEventHandler SetPasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AuthenticationResult Login(string username, string password, string department_code) {
            object[] results = this.Invoke("Login", new object[] {
                        username,
                        password,
                        department_code});
            return ((AuthenticationResult)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string username, string password, string department_code) {
            this.LoginAsync(username, password, department_code, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string username, string password, string department_code, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        username,
                        password,
                        department_code}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Logout", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AuthenticationResult Logout(string SessionId) {
            object[] results = this.Invoke("Logout", new object[] {
                        SessionId});
            return ((AuthenticationResult)(results[0]));
        }
        
        /// <remarks/>
        public void LogoutAsync(string SessionId) {
            this.LogoutAsync(SessionId, null);
        }
        
        /// <remarks/>
        public void LogoutAsync(string SessionId, object userState) {
            if ((this.LogoutOperationCompleted == null)) {
                this.LogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutOperationCompleted);
            }
            this.InvokeAsync("Logout", new object[] {
                        SessionId}, this.LogoutOperationCompleted, userState);
        }
        
        private void OnLogoutOperationCompleted(object arg) {
            if ((this.LogoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogoutCompleted(this, new LogoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWebSiteProperties", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebSitePropertiesResult GetWebSiteProperties() {
            object[] results = this.Invoke("GetWebSiteProperties", new object[0]);
            return ((WebSitePropertiesResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetWebSitePropertiesAsync() {
            this.GetWebSitePropertiesAsync(null);
        }
        
        /// <remarks/>
        public void GetWebSitePropertiesAsync(object userState) {
            if ((this.GetWebSitePropertiesOperationCompleted == null)) {
                this.GetWebSitePropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWebSitePropertiesOperationCompleted);
            }
            this.InvokeAsync("GetWebSiteProperties", new object[0], this.GetWebSitePropertiesOperationCompleted, userState);
        }
        
        private void OnGetWebSitePropertiesOperationCompleted(object arg) {
            if ((this.GetWebSitePropertiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWebSitePropertiesCompleted(this, new GetWebSitePropertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AuthenticationResult SetPassword(string SessionId, string OldPassword, string NewPassword) {
            object[] results = this.Invoke("SetPassword", new object[] {
                        SessionId,
                        OldPassword,
                        NewPassword});
            return ((AuthenticationResult)(results[0]));
        }
        
        /// <remarks/>
        public void SetPasswordAsync(string SessionId, string OldPassword, string NewPassword) {
            this.SetPasswordAsync(SessionId, OldPassword, NewPassword, null);
        }
        
        /// <remarks/>
        public void SetPasswordAsync(string SessionId, string OldPassword, string NewPassword, object userState) {
            if ((this.SetPasswordOperationCompleted == null)) {
                this.SetPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetPasswordOperationCompleted);
            }
            this.InvokeAsync("SetPassword", new object[] {
                        SessionId,
                        OldPassword,
                        NewPassword}, this.SetPasswordOperationCompleted, userState);
        }
        
        private void OnSetPasswordOperationCompleted(object arg) {
            if ((this.SetPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetPasswordCompleted(this, new SetPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticationResult : BaseResult {
        
        private userInfo userField;
        
        private System.Guid valueField;
        
        private department departmentField;
        
        private period periodField;
        
        private readgroup[] readGroupsField;
        
        private meterInfo[] authorizedMetersField;
        
        private HandTerminal[] authorizedTerminalsField;
        
        /// <remarks/>
        public userInfo User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public department Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public period Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        public readgroup[] ReadGroups {
            get {
                return this.readGroupsField;
            }
            set {
                this.readGroupsField = value;
            }
        }
        
        /// <remarks/>
        public meterInfo[] AuthorizedMeters {
            get {
                return this.authorizedMetersField;
            }
            set {
                this.authorizedMetersField = value;
            }
        }
        
        /// <remarks/>
        public HandTerminal[] AuthorizedTerminals {
            get {
                return this.authorizedTerminalsField;
            }
            set {
                this.authorizedTerminalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class userInfo : baseClass {
        
        private string windows_UserField;
        
        /// <remarks/>
        public string Windows_User {
            get {
                return this.windows_UserField;
            }
            set {
                this.windows_UserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(period))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(indexInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(meter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(meterInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(department))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(subscriber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tariffBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(group))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConstantValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HandTerminal))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(userInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class baseClass {
        
        private int idField;
        
        private string codeField;
        
        private string infoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WebSitePropertiesResult {
        
        private string caption1Field;
        
        private string caption2Field;
        
        private string imageField;
        
        /// <remarks/>
        public string Caption1 {
            get {
                return this.caption1Field;
            }
            set {
                this.caption1Field = value;
            }
        }
        
        /// <remarks/>
        public string Caption2 {
            get {
                return this.caption2Field;
            }
            set {
                this.caption2Field = value;
            }
        }
        
        /// <remarks/>
        public string Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class readgroup {
        
        private int idField;
        
        private System.DateTime dateTimeField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsumptionLine {
        
        private int iNDEX_IDField;
        
        private System.DateTime dATETIME_Field;
        
        private string iNDEX_CODEField;
        
        private string iNDEX_INFOField;
        
        private double bEGIN_INDEXField;
        
        private double eND_INDEXField;
        
        private double iNDEX_AMOUNTField;
        
        private bool uSE_MULTIPLIERField;
        
        private double mULTIPLIERField;
        
        private double aDDITIONAL_AMOUNTField;
        
        private double aMOUNTField;
        
        private string fORMULAField;
        
        private string sTATEField;
        
        private int oRDERBYField;
        
        private string uNITField;
        
        /// <remarks/>
        public int INDEX_ID {
            get {
                return this.iNDEX_IDField;
            }
            set {
                this.iNDEX_IDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DATETIME_ {
            get {
                return this.dATETIME_Field;
            }
            set {
                this.dATETIME_Field = value;
            }
        }
        
        /// <remarks/>
        public string INDEX_CODE {
            get {
                return this.iNDEX_CODEField;
            }
            set {
                this.iNDEX_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string INDEX_INFO {
            get {
                return this.iNDEX_INFOField;
            }
            set {
                this.iNDEX_INFOField = value;
            }
        }
        
        /// <remarks/>
        public double BEGIN_INDEX {
            get {
                return this.bEGIN_INDEXField;
            }
            set {
                this.bEGIN_INDEXField = value;
            }
        }
        
        /// <remarks/>
        public double END_INDEX {
            get {
                return this.eND_INDEXField;
            }
            set {
                this.eND_INDEXField = value;
            }
        }
        
        /// <remarks/>
        public double INDEX_AMOUNT {
            get {
                return this.iNDEX_AMOUNTField;
            }
            set {
                this.iNDEX_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        public bool USE_MULTIPLIER {
            get {
                return this.uSE_MULTIPLIERField;
            }
            set {
                this.uSE_MULTIPLIERField = value;
            }
        }
        
        /// <remarks/>
        public double MULTIPLIER {
            get {
                return this.mULTIPLIERField;
            }
            set {
                this.mULTIPLIERField = value;
            }
        }
        
        /// <remarks/>
        public double ADDITIONAL_AMOUNT {
            get {
                return this.aDDITIONAL_AMOUNTField;
            }
            set {
                this.aDDITIONAL_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        public double AMOUNT {
            get {
                return this.aMOUNTField;
            }
            set {
                this.aMOUNTField = value;
            }
        }
        
        /// <remarks/>
        public string FORMULA {
            get {
                return this.fORMULAField;
            }
            set {
                this.fORMULAField = value;
            }
        }
        
        /// <remarks/>
        public string STATE {
            get {
                return this.sTATEField;
            }
            set {
                this.sTATEField = value;
            }
        }
        
        /// <remarks/>
        public int ORDERBY {
            get {
                return this.oRDERBYField;
            }
            set {
                this.oRDERBYField = value;
            }
        }
        
        /// <remarks/>
        public string UNIT {
            get {
                return this.uNITField;
            }
            set {
                this.uNITField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class indexValue {
        
        private indexInfo indexInfoField;
        
        private byte departmentIdField;
        
        private int idField;
        
        private System.DateTime dateTimeField;
        
        private int subscriberIdField;
        
        private int meterIdField;
        
        private double rawValueField;
        
        private double multiplierField;
        
        private double fixedValueField;
        
        private int statusField;
        
        private int referenceField;
        
        private int sourceField;
        
        private int createdByField;
        
        private System.DateTime createdDateField;
        
        private string tariffFormulaField;
        
        private int orderByField;
        
        /// <remarks/>
        public indexInfo IndexInfo {
            get {
                return this.indexInfoField;
            }
            set {
                this.indexInfoField = value;
            }
        }
        
        /// <remarks/>
        public byte departmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        public int SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        public int MeterId {
            get {
                return this.meterIdField;
            }
            set {
                this.meterIdField = value;
            }
        }
        
        /// <remarks/>
        public double RawValue {
            get {
                return this.rawValueField;
            }
            set {
                this.rawValueField = value;
            }
        }
        
        /// <remarks/>
        public double Multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
        
        /// <remarks/>
        public double FixedValue {
            get {
                return this.fixedValueField;
            }
            set {
                this.fixedValueField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public int Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public int CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public string TariffFormula {
            get {
                return this.tariffFormulaField;
            }
            set {
                this.tariffFormulaField = value;
            }
        }
        
        /// <remarks/>
        public int OrderBy {
            get {
                return this.orderByField;
            }
            set {
                this.orderByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class indexInfo : baseClass {
        
        private string unitField;
        
        private bool useMultiplierField;
        
        private int dataTypeField;
        
        private string dataTypeInfoField;
        
        private bool webVisibleField;
        
        private bool webMainPageField;
        
        private bool isOrderedField;
        
        /// <remarks/>
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        public bool UseMultiplier {
            get {
                return this.useMultiplierField;
            }
            set {
                this.useMultiplierField = value;
            }
        }
        
        /// <remarks/>
        public int DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DataTypeInfo {
            get {
                return this.dataTypeInfoField;
            }
            set {
                this.dataTypeInfoField = value;
            }
        }
        
        /// <remarks/>
        public bool WebVisible {
            get {
                return this.webVisibleField;
            }
            set {
                this.webVisibleField = value;
            }
        }
        
        /// <remarks/>
        public bool WebMainPage {
            get {
                return this.webMainPageField;
            }
            set {
                this.webMainPageField = value;
            }
        }
        
        /// <remarks/>
        public bool IsOrdered {
            get {
                return this.isOrderedField;
            }
            set {
                this.isOrderedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class meterMechanic {
        
        private int lineNoField;
        
        private string serialField;
        
        private string typeField;
        
        private string classField;
        
        private string markField;
        
        private string modelField;
        
        private string sealNumberField;
        
        private string prodYearField;
        
        private System.DateTime calibrationDateField;
        
        private double qMinField;
        
        private double qMaxField;
        
        private double pressValueField;
        
        private string radiusField;
        
        /// <remarks/>
        public int LineNo {
            get {
                return this.lineNoField;
            }
            set {
                this.lineNoField = value;
            }
        }
        
        /// <remarks/>
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        public string Mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string SealNumber {
            get {
                return this.sealNumberField;
            }
            set {
                this.sealNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ProdYear {
            get {
                return this.prodYearField;
            }
            set {
                this.prodYearField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CalibrationDate {
            get {
                return this.calibrationDateField;
            }
            set {
                this.calibrationDateField = value;
            }
        }
        
        /// <remarks/>
        public double QMin {
            get {
                return this.qMinField;
            }
            set {
                this.qMinField = value;
            }
        }
        
        /// <remarks/>
        public double QMax {
            get {
                return this.qMaxField;
            }
            set {
                this.qMaxField = value;
            }
        }
        
        /// <remarks/>
        public double PressValue {
            get {
                return this.pressValueField;
            }
            set {
                this.pressValueField = value;
            }
        }
        
        /// <remarks/>
        public string Radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class taxInfo {
        
        private string taxTypeField;
        
        private string valueField;
        
        private string taxOfficeField;
        
        /// <remarks/>
        public string TaxType {
            get {
                return this.taxTypeField;
            }
            set {
                this.taxTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string TaxOffice {
            get {
                return this.taxOfficeField;
            }
            set {
                this.taxOfficeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class contacts {
        
        private string phone1Field;
        
        private string phone2Field;
        
        private string faxField;
        
        private string gsmField;
        
        private string gsm2Field;
        
        private string gsm3Field;
        
        private string emailField;
        
        private string webField;
        
        /// <remarks/>
        public string Phone1 {
            get {
                return this.phone1Field;
            }
            set {
                this.phone1Field = value;
            }
        }
        
        /// <remarks/>
        public string Phone2 {
            get {
                return this.phone2Field;
            }
            set {
                this.phone2Field = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string Gsm {
            get {
                return this.gsmField;
            }
            set {
                this.gsmField = value;
            }
        }
        
        /// <remarks/>
        public string Gsm2 {
            get {
                return this.gsm2Field;
            }
            set {
                this.gsm2Field = value;
            }
        }
        
        /// <remarks/>
        public string Gsm3 {
            get {
                return this.gsm3Field;
            }
            set {
                this.gsm3Field = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Web {
            get {
                return this.webField;
            }
            set {
                this.webField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class address {
        
        private string addressTypeField;
        
        private string line1Field;
        
        private string line2Field;
        
        private string line3Field;
        
        private int townIdField;
        
        private string townField;
        
        private int cityIdField;
        
        private string cityField;
        
        /// <remarks/>
        public string addressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        /// <remarks/>
        public string Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
            }
        }
        
        /// <remarks/>
        public string Line3 {
            get {
                return this.line3Field;
            }
            set {
                this.line3Field = value;
            }
        }
        
        /// <remarks/>
        public int TownId {
            get {
                return this.townIdField;
            }
            set {
                this.townIdField = value;
            }
        }
        
        /// <remarks/>
        public string Town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        public int CityId {
            get {
                return this.cityIdField;
            }
            set {
                this.cityIdField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Message {
        
        private string resultTypeField;
        
        private int idField;
        
        private string infoField;
        
        /// <remarks/>
        public string ResultType {
            get {
                return this.resultTypeField;
            }
            set {
                this.resultTypeField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticationResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseResult {
        
        private Message resultField;
        
        /// <remarks/>
        public Message Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class period : baseClass {
        
        private System.DateTime beginDateField;
        
        private System.DateTime endDateField;
        
        private System.DateTime lastPayDateField;
        
        private System.DateTime invoiceDateField;
        
        /// <remarks/>
        public System.DateTime BeginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastPayDate {
            get {
                return this.lastPayDateField;
            }
            set {
                this.lastPayDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(meterInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class meter : baseClass {
        
        private string markField;
        
        private string modelField;
        
        private string driverField;
        
        private double contractPowerField;
        
        private double settedPowerField;
        
        private double multiplierField;
        
        private int subscriberIdField;
        
        private int departmentIdField;
        
        private string departmentCodeField;
        
        private string subscriberCodeField;
        
        private string meterYearField;
        
        private int profilePeriodField;
        
        private int usingPlaceField;
        
        private string usingPlaceStringField;
        
        private bool cancelledField;
        
        private string subscriberAttachStateField;
        
        private meterMechanic[] mechanicsField;
        
        /// <remarks/>
        public string Mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string Driver {
            get {
                return this.driverField;
            }
            set {
                this.driverField = value;
            }
        }
        
        /// <remarks/>
        public double ContractPower {
            get {
                return this.contractPowerField;
            }
            set {
                this.contractPowerField = value;
            }
        }
        
        /// <remarks/>
        public double SettedPower {
            get {
                return this.settedPowerField;
            }
            set {
                this.settedPowerField = value;
            }
        }
        
        /// <remarks/>
        public double Multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
        
        /// <remarks/>
        public int SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        public int DepartmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentCode {
            get {
                return this.departmentCodeField;
            }
            set {
                this.departmentCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SubscriberCode {
            get {
                return this.subscriberCodeField;
            }
            set {
                this.subscriberCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MeterYear {
            get {
                return this.meterYearField;
            }
            set {
                this.meterYearField = value;
            }
        }
        
        /// <remarks/>
        public int ProfilePeriod {
            get {
                return this.profilePeriodField;
            }
            set {
                this.profilePeriodField = value;
            }
        }
        
        /// <remarks/>
        public int UsingPlace {
            get {
                return this.usingPlaceField;
            }
            set {
                this.usingPlaceField = value;
            }
        }
        
        /// <remarks/>
        public string UsingPlaceString {
            get {
                return this.usingPlaceStringField;
            }
            set {
                this.usingPlaceStringField = value;
            }
        }
        
        /// <remarks/>
        public bool Cancelled {
            get {
                return this.cancelledField;
            }
            set {
                this.cancelledField = value;
            }
        }
        
        /// <remarks/>
        public string subscriberAttachState {
            get {
                return this.subscriberAttachStateField;
            }
            set {
                this.subscriberAttachStateField = value;
            }
        }
        
        /// <remarks/>
        public meterMechanic[] Mechanics {
            get {
                return this.mechanicsField;
            }
            set {
                this.mechanicsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class meterInfo : meter {
        
        private System.DateTime firstDateField;
        
        private System.DateTime lastDateField;
        
        private indexValue[] firstValuesField;
        
        private indexValue[] lastValuesField;
        
        private ConsumptionLine[] consumptionsField;
        
        private subscriber subscriberField;
        
        private string typeStrField;
        
        /// <remarks/>
        public System.DateTime FirstDate {
            get {
                return this.firstDateField;
            }
            set {
                this.firstDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastDate {
            get {
                return this.lastDateField;
            }
            set {
                this.lastDateField = value;
            }
        }
        
        /// <remarks/>
        public indexValue[] FirstValues {
            get {
                return this.firstValuesField;
            }
            set {
                this.firstValuesField = value;
            }
        }
        
        /// <remarks/>
        public indexValue[] LastValues {
            get {
                return this.lastValuesField;
            }
            set {
                this.lastValuesField = value;
            }
        }
        
        /// <remarks/>
        public ConsumptionLine[] Consumptions {
            get {
                return this.consumptionsField;
            }
            set {
                this.consumptionsField = value;
            }
        }
        
        /// <remarks/>
        public subscriber Subscriber {
            get {
                return this.subscriberField;
            }
            set {
                this.subscriberField = value;
            }
        }
        
        /// <remarks/>
        public string TypeStr {
            get {
                return this.typeStrField;
            }
            set {
                this.typeStrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class subscriber : baseClass {
        
        private department departmentField;
        
        private baseClass subscriberTypeField;
        
        private tariffBase tariffField;
        
        private group groupField;
        
        private taxInfo taxInfoField;
        
        private address addressField;
        
        private contacts contactsField;
        
        private meter mainMeterField;
        
        private string uniqueNumberField;
        
        private string pmumIdField;
        
        private int orderField;
        
        private meter[] subMetersField;
        
        private string relevantField;
        
        private ConstantValue[] constantsField;
        
        /// <remarks/>
        public department Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public baseClass SubscriberType {
            get {
                return this.subscriberTypeField;
            }
            set {
                this.subscriberTypeField = value;
            }
        }
        
        /// <remarks/>
        public tariffBase Tariff {
            get {
                return this.tariffField;
            }
            set {
                this.tariffField = value;
            }
        }
        
        /// <remarks/>
        public group Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        public taxInfo TaxInfo {
            get {
                return this.taxInfoField;
            }
            set {
                this.taxInfoField = value;
            }
        }
        
        /// <remarks/>
        public address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public contacts Contacts {
            get {
                return this.contactsField;
            }
            set {
                this.contactsField = value;
            }
        }
        
        /// <remarks/>
        public meter MainMeter {
            get {
                return this.mainMeterField;
            }
            set {
                this.mainMeterField = value;
            }
        }
        
        /// <remarks/>
        public string UniqueNumber {
            get {
                return this.uniqueNumberField;
            }
            set {
                this.uniqueNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PmumId {
            get {
                return this.pmumIdField;
            }
            set {
                this.pmumIdField = value;
            }
        }
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        public meter[] SubMeters {
            get {
                return this.subMetersField;
            }
            set {
                this.subMetersField = value;
            }
        }
        
        /// <remarks/>
        public string Relevant {
            get {
                return this.relevantField;
            }
            set {
                this.relevantField = value;
            }
        }
        
        /// <remarks/>
        public ConstantValue[] Constants {
            get {
                return this.constantsField;
            }
            set {
                this.constantsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class department : baseClass {
        
        private int departmentTypeField;
        
        private string relevantField;
        
        private address adresField;
        
        private contacts contactField;
        
        private taxInfo taxInfoField;
        
        private string prefixEInvoiceField;
        
        private string prefixEArchiveField;
        
        /// <remarks/>
        public int departmentType {
            get {
                return this.departmentTypeField;
            }
            set {
                this.departmentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Relevant {
            get {
                return this.relevantField;
            }
            set {
                this.relevantField = value;
            }
        }
        
        /// <remarks/>
        public address Adres {
            get {
                return this.adresField;
            }
            set {
                this.adresField = value;
            }
        }
        
        /// <remarks/>
        public contacts Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public taxInfo taxInfo {
            get {
                return this.taxInfoField;
            }
            set {
                this.taxInfoField = value;
            }
        }
        
        /// <remarks/>
        public string PrefixEInvoice {
            get {
                return this.prefixEInvoiceField;
            }
            set {
                this.prefixEInvoiceField = value;
            }
        }
        
        /// <remarks/>
        public string PrefixEArchive {
            get {
                return this.prefixEArchiveField;
            }
            set {
                this.prefixEArchiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tariffBase : baseClass {
        
        private string code1Field;
        
        private string code2Field;
        
        private string code3Field;
        
        /// <remarks/>
        public string Code1 {
            get {
                return this.code1Field;
            }
            set {
                this.code1Field = value;
            }
        }
        
        /// <remarks/>
        public string Code2 {
            get {
                return this.code2Field;
            }
            set {
                this.code2Field = value;
            }
        }
        
        /// <remarks/>
        public string Code3 {
            get {
                return this.code3Field;
            }
            set {
                this.code3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class group : baseClass {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConstantValue : baseClass {
        
        private int orderByField;
        
        private double valueField;
        
        private double priceField;
        
        private double totalField;
        
        /// <remarks/>
        public int OrderBy {
            get {
                return this.orderByField;
            }
            set {
                this.orderByField = value;
            }
        }
        
        /// <remarks/>
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public double Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public double Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HandTerminal : baseClass {
        
        private int allSubscribersField;
        
        private decimal multiplierField;
        
        /// <remarks/>
        public int AllSubscribers {
            get {
                return this.allSubscribersField;
            }
            set {
                this.allSubscribersField = value;
            }
        }
        
        /// <remarks/>
        public decimal Multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthenticationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthenticationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LogoutCompletedEventHandler(object sender, LogoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthenticationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthenticationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetWebSitePropertiesCompletedEventHandler(object sender, GetWebSitePropertiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWebSitePropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWebSitePropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebSitePropertiesResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebSitePropertiesResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SetPasswordCompletedEventHandler(object sender, SetPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthenticationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthenticationResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591