//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace App4.Subscribers {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SubscribersSoap", Namespace="http://tempuri.org/")]
    public partial class Subscribers : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDepartmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompanyGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSubscribersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSubscribersByTerminalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSubscriberOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTaxInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Subscribers() {
            this.Url = "http://95.6.50.139:90/Services/Subscribers.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDepartmentsCompletedEventHandler GetDepartmentsCompleted;
        
        /// <remarks/>
        public event GetCompanyGroupsCompletedEventHandler GetCompanyGroupsCompleted;
        
        /// <remarks/>
        public event GetSubscribersCompletedEventHandler GetSubscribersCompleted;
        
        /// <remarks/>
        public event GetSubscribersByTerminalCompletedEventHandler GetSubscribersByTerminalCompleted;
        
        /// <remarks/>
        public event GetSubscriberCompletedEventHandler GetSubscriberCompleted;
        
        /// <remarks/>
        public event UpdateAddressCompletedEventHandler UpdateAddressCompleted;
        
        /// <remarks/>
        public event UpdateContactCompletedEventHandler UpdateContactCompleted;
        
        /// <remarks/>
        public event UpdateTaxInfoCompletedEventHandler UpdateTaxInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDepartments", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DepartmentListResult GetDepartments(string SessionId) {
            object[] results = this.Invoke("GetDepartments", new object[] {
                        SessionId});
            return ((DepartmentListResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentsAsync(string SessionId) {
            this.GetDepartmentsAsync(SessionId, null);
        }
        
        /// <remarks/>
        public void GetDepartmentsAsync(string SessionId, object userState) {
            if ((this.GetDepartmentsOperationCompleted == null)) {
                this.GetDepartmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentsOperationCompleted);
            }
            this.InvokeAsync("GetDepartments", new object[] {
                        SessionId}, this.GetDepartmentsOperationCompleted, userState);
        }
        
        private void OnGetDepartmentsOperationCompleted(object arg) {
            if ((this.GetDepartmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentsCompleted(this, new GetDepartmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCompanyGroups", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GroupListResult GetCompanyGroups(string SessionId, int departmentId) {
            object[] results = this.Invoke("GetCompanyGroups", new object[] {
                        SessionId,
                        departmentId});
            return ((GroupListResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetCompanyGroupsAsync(string SessionId, int departmentId) {
            this.GetCompanyGroupsAsync(SessionId, departmentId, null);
        }
        
        /// <remarks/>
        public void GetCompanyGroupsAsync(string SessionId, int departmentId, object userState) {
            if ((this.GetCompanyGroupsOperationCompleted == null)) {
                this.GetCompanyGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompanyGroupsOperationCompleted);
            }
            this.InvokeAsync("GetCompanyGroups", new object[] {
                        SessionId,
                        departmentId}, this.GetCompanyGroupsOperationCompleted, userState);
        }
        
        private void OnGetCompanyGroupsOperationCompleted(object arg) {
            if ((this.GetCompanyGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompanyGroupsCompleted(this, new GetCompanyGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSubscribers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SubscriberListResult GetSubscribers(string SessionId, int departmentId, int CompanygroupId) {
            object[] results = this.Invoke("GetSubscribers", new object[] {
                        SessionId,
                        departmentId,
                        CompanygroupId});
            return ((SubscriberListResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetSubscribersAsync(string SessionId, int departmentId, int CompanygroupId) {
            this.GetSubscribersAsync(SessionId, departmentId, CompanygroupId, null);
        }
        
        /// <remarks/>
        public void GetSubscribersAsync(string SessionId, int departmentId, int CompanygroupId, object userState) {
            if ((this.GetSubscribersOperationCompleted == null)) {
                this.GetSubscribersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSubscribersOperationCompleted);
            }
            this.InvokeAsync("GetSubscribers", new object[] {
                        SessionId,
                        departmentId,
                        CompanygroupId}, this.GetSubscribersOperationCompleted, userState);
        }
        
        private void OnGetSubscribersOperationCompleted(object arg) {
            if ((this.GetSubscribersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSubscribersCompleted(this, new GetSubscribersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSubscribersByTerminal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SubscriberListResult GetSubscribersByTerminal(string SessionId, int departmentId, int TerminalId) {
            object[] results = this.Invoke("GetSubscribersByTerminal", new object[] {
                        SessionId,
                        departmentId,
                        TerminalId});
            return ((SubscriberListResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetSubscribersByTerminalAsync(string SessionId, int departmentId, int TerminalId) {
            this.GetSubscribersByTerminalAsync(SessionId, departmentId, TerminalId, null);
        }
        
        /// <remarks/>
        public void GetSubscribersByTerminalAsync(string SessionId, int departmentId, int TerminalId, object userState) {
            if ((this.GetSubscribersByTerminalOperationCompleted == null)) {
                this.GetSubscribersByTerminalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSubscribersByTerminalOperationCompleted);
            }
            this.InvokeAsync("GetSubscribersByTerminal", new object[] {
                        SessionId,
                        departmentId,
                        TerminalId}, this.GetSubscribersByTerminalOperationCompleted, userState);
        }
        
        private void OnGetSubscribersByTerminalOperationCompleted(object arg) {
            if ((this.GetSubscribersByTerminalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSubscribersByTerminalCompleted(this, new GetSubscribersByTerminalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSubscriber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SubscriberResult GetSubscriber(string SessionId, int departmentId, int subscriberId) {
            object[] results = this.Invoke("GetSubscriber", new object[] {
                        SessionId,
                        departmentId,
                        subscriberId});
            return ((SubscriberResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetSubscriberAsync(string SessionId, int departmentId, int subscriberId) {
            this.GetSubscriberAsync(SessionId, departmentId, subscriberId, null);
        }
        
        /// <remarks/>
        public void GetSubscriberAsync(string SessionId, int departmentId, int subscriberId, object userState) {
            if ((this.GetSubscriberOperationCompleted == null)) {
                this.GetSubscriberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSubscriberOperationCompleted);
            }
            this.InvokeAsync("GetSubscriber", new object[] {
                        SessionId,
                        departmentId,
                        subscriberId}, this.GetSubscriberOperationCompleted, userState);
        }
        
        private void OnGetSubscriberOperationCompleted(object arg) {
            if ((this.GetSubscriberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSubscriberCompleted(this, new GetSubscriberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateAddress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BaseResult UpdateAddress(string SessionId, int departmentId, int subscriberId, address Address) {
            object[] results = this.Invoke("UpdateAddress", new object[] {
                        SessionId,
                        departmentId,
                        subscriberId,
                        Address});
            return ((BaseResult)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAddressAsync(string SessionId, int departmentId, int subscriberId, address Address) {
            this.UpdateAddressAsync(SessionId, departmentId, subscriberId, Address, null);
        }
        
        /// <remarks/>
        public void UpdateAddressAsync(string SessionId, int departmentId, int subscriberId, address Address, object userState) {
            if ((this.UpdateAddressOperationCompleted == null)) {
                this.UpdateAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAddressOperationCompleted);
            }
            this.InvokeAsync("UpdateAddress", new object[] {
                        SessionId,
                        departmentId,
                        subscriberId,
                        Address}, this.UpdateAddressOperationCompleted, userState);
        }
        
        private void OnUpdateAddressOperationCompleted(object arg) {
            if ((this.UpdateAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateAddressCompleted(this, new UpdateAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateContact", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BaseResult UpdateContact(string SessionId, int departmentId, int subscriberId, contacts Contact) {
            object[] results = this.Invoke("UpdateContact", new object[] {
                        SessionId,
                        departmentId,
                        subscriberId,
                        Contact});
            return ((BaseResult)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateContactAsync(string SessionId, int departmentId, int subscriberId, contacts Contact) {
            this.UpdateContactAsync(SessionId, departmentId, subscriberId, Contact, null);
        }
        
        /// <remarks/>
        public void UpdateContactAsync(string SessionId, int departmentId, int subscriberId, contacts Contact, object userState) {
            if ((this.UpdateContactOperationCompleted == null)) {
                this.UpdateContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateContactOperationCompleted);
            }
            this.InvokeAsync("UpdateContact", new object[] {
                        SessionId,
                        departmentId,
                        subscriberId,
                        Contact}, this.UpdateContactOperationCompleted, userState);
        }
        
        private void OnUpdateContactOperationCompleted(object arg) {
            if ((this.UpdateContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateContactCompleted(this, new UpdateContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateTaxInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BaseResult UpdateTaxInfo(string SessionId, int departmentId, int subscriberId, taxInfo TaxInfo) {
            object[] results = this.Invoke("UpdateTaxInfo", new object[] {
                        SessionId,
                        departmentId,
                        subscriberId,
                        TaxInfo});
            return ((BaseResult)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTaxInfoAsync(string SessionId, int departmentId, int subscriberId, taxInfo TaxInfo) {
            this.UpdateTaxInfoAsync(SessionId, departmentId, subscriberId, TaxInfo, null);
        }
        
        /// <remarks/>
        public void UpdateTaxInfoAsync(string SessionId, int departmentId, int subscriberId, taxInfo TaxInfo, object userState) {
            if ((this.UpdateTaxInfoOperationCompleted == null)) {
                this.UpdateTaxInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTaxInfoOperationCompleted);
            }
            this.InvokeAsync("UpdateTaxInfo", new object[] {
                        SessionId,
                        departmentId,
                        subscriberId,
                        TaxInfo}, this.UpdateTaxInfoOperationCompleted, userState);
        }
        
        private void OnUpdateTaxInfoOperationCompleted(object arg) {
            if ((this.UpdateTaxInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTaxInfoCompleted(this, new UpdateTaxInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DepartmentListResult : BaseResult {
        
        private department[] valueField;
        
        /// <remarks/>
        public department[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class department : baseClass {
        
        private int departmentTypeField;
        
        private string relevantField;
        
        private address adresField;
        
        private contacts contactField;
        
        private taxInfo taxInfoField;
        
        private string prefixEInvoiceField;
        
        private string prefixEArchiveField;
        
        /// <remarks/>
        public int departmentType {
            get {
                return this.departmentTypeField;
            }
            set {
                this.departmentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Relevant {
            get {
                return this.relevantField;
            }
            set {
                this.relevantField = value;
            }
        }
        
        /// <remarks/>
        public address Adres {
            get {
                return this.adresField;
            }
            set {
                this.adresField = value;
            }
        }
        
        /// <remarks/>
        public contacts Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public taxInfo taxInfo {
            get {
                return this.taxInfoField;
            }
            set {
                this.taxInfoField = value;
            }
        }
        
        /// <remarks/>
        public string PrefixEInvoice {
            get {
                return this.prefixEInvoiceField;
            }
            set {
                this.prefixEInvoiceField = value;
            }
        }
        
        /// <remarks/>
        public string PrefixEArchive {
            get {
                return this.prefixEArchiveField;
            }
            set {
                this.prefixEArchiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class address {
        
        private string addressTypeField;
        
        private string line1Field;
        
        private string line2Field;
        
        private string line3Field;
        
        private int townIdField;
        
        private string townField;
        
        private int cityIdField;
        
        private string cityField;
        
        /// <remarks/>
        public string addressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        /// <remarks/>
        public string Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
            }
        }
        
        /// <remarks/>
        public string Line3 {
            get {
                return this.line3Field;
            }
            set {
                this.line3Field = value;
            }
        }
        
        /// <remarks/>
        public int TownId {
            get {
                return this.townIdField;
            }
            set {
                this.townIdField = value;
            }
        }
        
        /// <remarks/>
        public string Town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        public int CityId {
            get {
                return this.cityIdField;
            }
            set {
                this.cityIdField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class meterMechanic {
        
        private int lineNoField;
        
        private string serialField;
        
        private string typeField;
        
        private string classField;
        
        private string markField;
        
        private string modelField;
        
        private string sealNumberField;
        
        private string prodYearField;
        
        private System.DateTime calibrationDateField;
        
        private double qMinField;
        
        private double qMaxField;
        
        private double pressValueField;
        
        private string radiusField;
        
        /// <remarks/>
        public int LineNo {
            get {
                return this.lineNoField;
            }
            set {
                this.lineNoField = value;
            }
        }
        
        /// <remarks/>
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        public string Mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string SealNumber {
            get {
                return this.sealNumberField;
            }
            set {
                this.sealNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ProdYear {
            get {
                return this.prodYearField;
            }
            set {
                this.prodYearField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CalibrationDate {
            get {
                return this.calibrationDateField;
            }
            set {
                this.calibrationDateField = value;
            }
        }
        
        /// <remarks/>
        public double QMin {
            get {
                return this.qMinField;
            }
            set {
                this.qMinField = value;
            }
        }
        
        /// <remarks/>
        public double QMax {
            get {
                return this.qMaxField;
            }
            set {
                this.qMaxField = value;
            }
        }
        
        /// <remarks/>
        public double PressValue {
            get {
                return this.pressValueField;
            }
            set {
                this.pressValueField = value;
            }
        }
        
        /// <remarks/>
        public string Radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class taxInfo {
        
        private string taxTypeField;
        
        private string valueField;
        
        private string taxOfficeField;
        
        /// <remarks/>
        public string TaxType {
            get {
                return this.taxTypeField;
            }
            set {
                this.taxTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string TaxOffice {
            get {
                return this.taxOfficeField;
            }
            set {
                this.taxOfficeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class contacts {
        
        private string phone1Field;
        
        private string phone2Field;
        
        private string faxField;
        
        private string gsmField;
        
        private string gsm2Field;
        
        private string gsm3Field;
        
        private string emailField;
        
        private string webField;
        
        /// <remarks/>
        public string Phone1 {
            get {
                return this.phone1Field;
            }
            set {
                this.phone1Field = value;
            }
        }
        
        /// <remarks/>
        public string Phone2 {
            get {
                return this.phone2Field;
            }
            set {
                this.phone2Field = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string Gsm {
            get {
                return this.gsmField;
            }
            set {
                this.gsmField = value;
            }
        }
        
        /// <remarks/>
        public string Gsm2 {
            get {
                return this.gsm2Field;
            }
            set {
                this.gsm2Field = value;
            }
        }
        
        /// <remarks/>
        public string Gsm3 {
            get {
                return this.gsm3Field;
            }
            set {
                this.gsm3Field = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Web {
            get {
                return this.webField;
            }
            set {
                this.webField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConstantValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(meter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(group))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tariffBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(department))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(subscriber))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class baseClass {
        
        private int idField;
        
        private string codeField;
        
        private string infoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConstantValue : baseClass {
        
        private int orderByField;
        
        private double valueField;
        
        private double priceField;
        
        private double totalField;
        
        /// <remarks/>
        public int OrderBy {
            get {
                return this.orderByField;
            }
            set {
                this.orderByField = value;
            }
        }
        
        /// <remarks/>
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public double Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public double Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class meter : baseClass {
        
        private string markField;
        
        private string modelField;
        
        private string driverField;
        
        private double contractPowerField;
        
        private double settedPowerField;
        
        private double multiplierField;
        
        private int subscriberIdField;
        
        private int departmentIdField;
        
        private string departmentCodeField;
        
        private string subscriberCodeField;
        
        private string meterYearField;
        
        private int profilePeriodField;
        
        private int usingPlaceField;
        
        private string usingPlaceStringField;
        
        private bool cancelledField;
        
        private string subscriberAttachStateField;
        
        private meterMechanic[] mechanicsField;
        
        /// <remarks/>
        public string Mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string Driver {
            get {
                return this.driverField;
            }
            set {
                this.driverField = value;
            }
        }
        
        /// <remarks/>
        public double ContractPower {
            get {
                return this.contractPowerField;
            }
            set {
                this.contractPowerField = value;
            }
        }
        
        /// <remarks/>
        public double SettedPower {
            get {
                return this.settedPowerField;
            }
            set {
                this.settedPowerField = value;
            }
        }
        
        /// <remarks/>
        public double Multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
        
        /// <remarks/>
        public int SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
            }
        }
        
        /// <remarks/>
        public int DepartmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentCode {
            get {
                return this.departmentCodeField;
            }
            set {
                this.departmentCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SubscriberCode {
            get {
                return this.subscriberCodeField;
            }
            set {
                this.subscriberCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MeterYear {
            get {
                return this.meterYearField;
            }
            set {
                this.meterYearField = value;
            }
        }
        
        /// <remarks/>
        public int ProfilePeriod {
            get {
                return this.profilePeriodField;
            }
            set {
                this.profilePeriodField = value;
            }
        }
        
        /// <remarks/>
        public int UsingPlace {
            get {
                return this.usingPlaceField;
            }
            set {
                this.usingPlaceField = value;
            }
        }
        
        /// <remarks/>
        public string UsingPlaceString {
            get {
                return this.usingPlaceStringField;
            }
            set {
                this.usingPlaceStringField = value;
            }
        }
        
        /// <remarks/>
        public bool Cancelled {
            get {
                return this.cancelledField;
            }
            set {
                this.cancelledField = value;
            }
        }
        
        /// <remarks/>
        public string subscriberAttachState {
            get {
                return this.subscriberAttachStateField;
            }
            set {
                this.subscriberAttachStateField = value;
            }
        }
        
        /// <remarks/>
        public meterMechanic[] Mechanics {
            get {
                return this.mechanicsField;
            }
            set {
                this.mechanicsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class group : baseClass {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tariffBase : baseClass {
        
        private string code1Field;
        
        private string code2Field;
        
        private string code3Field;
        
        /// <remarks/>
        public string Code1 {
            get {
                return this.code1Field;
            }
            set {
                this.code1Field = value;
            }
        }
        
        /// <remarks/>
        public string Code2 {
            get {
                return this.code2Field;
            }
            set {
                this.code2Field = value;
            }
        }
        
        /// <remarks/>
        public string Code3 {
            get {
                return this.code3Field;
            }
            set {
                this.code3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class subscriber : baseClass {
        
        private department departmentField;
        
        private baseClass subscriberTypeField;
        
        private tariffBase tariffField;
        
        private group groupField;
        
        private taxInfo taxInfoField;
        
        private address addressField;
        
        private contacts contactsField;
        
        private meter mainMeterField;
        
        private string uniqueNumberField;
        
        private string pmumIdField;
        
        private int orderField;
        
        private meter[] subMetersField;
        
        private string relevantField;
        
        private ConstantValue[] constantsField;
        
        /// <remarks/>
        public department Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public baseClass SubscriberType {
            get {
                return this.subscriberTypeField;
            }
            set {
                this.subscriberTypeField = value;
            }
        }
        
        /// <remarks/>
        public tariffBase Tariff {
            get {
                return this.tariffField;
            }
            set {
                this.tariffField = value;
            }
        }
        
        /// <remarks/>
        public group Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        public taxInfo TaxInfo {
            get {
                return this.taxInfoField;
            }
            set {
                this.taxInfoField = value;
            }
        }
        
        /// <remarks/>
        public address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public contacts Contacts {
            get {
                return this.contactsField;
            }
            set {
                this.contactsField = value;
            }
        }
        
        /// <remarks/>
        public meter MainMeter {
            get {
                return this.mainMeterField;
            }
            set {
                this.mainMeterField = value;
            }
        }
        
        /// <remarks/>
        public string UniqueNumber {
            get {
                return this.uniqueNumberField;
            }
            set {
                this.uniqueNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PmumId {
            get {
                return this.pmumIdField;
            }
            set {
                this.pmumIdField = value;
            }
        }
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        public meter[] SubMeters {
            get {
                return this.subMetersField;
            }
            set {
                this.subMetersField = value;
            }
        }
        
        /// <remarks/>
        public string Relevant {
            get {
                return this.relevantField;
            }
            set {
                this.relevantField = value;
            }
        }
        
        /// <remarks/>
        public ConstantValue[] Constants {
            get {
                return this.constantsField;
            }
            set {
                this.constantsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Message {
        
        private string resultTypeField;
        
        private int idField;
        
        private string infoField;
        
        /// <remarks/>
        public string ResultType {
            get {
                return this.resultTypeField;
            }
            set {
                this.resultTypeField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubscriberResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GroupListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubscriberListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DepartmentListResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseResult {
        
        private Message resultField;
        
        /// <remarks/>
        public Message Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SubscriberResult : BaseResult {
        
        private subscriber valueField;
        
        /// <remarks/>
        public subscriber Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GroupListResult : BaseResult {
        
        private group[] valueField;
        
        /// <remarks/>
        public group[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SubscriberListResult : BaseResult {
        
        private subscriber[] valueField;
        
        /// <remarks/>
        public subscriber[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDepartmentsCompletedEventHandler(object sender, GetDepartmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DepartmentListResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DepartmentListResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetCompanyGroupsCompletedEventHandler(object sender, GetCompanyGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompanyGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompanyGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GroupListResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GroupListResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetSubscribersCompletedEventHandler(object sender, GetSubscribersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSubscribersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSubscribersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubscriberListResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubscriberListResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetSubscribersByTerminalCompletedEventHandler(object sender, GetSubscribersByTerminalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSubscribersByTerminalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSubscribersByTerminalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubscriberListResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubscriberListResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetSubscriberCompletedEventHandler(object sender, GetSubscriberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSubscriberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSubscriberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubscriberResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubscriberResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateAddressCompletedEventHandler(object sender, UpdateAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BaseResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BaseResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateContactCompletedEventHandler(object sender, UpdateContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BaseResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BaseResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateTaxInfoCompletedEventHandler(object sender, UpdateTaxInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTaxInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTaxInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BaseResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BaseResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591